grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 2
    verbose: 2

model_selection:
  module_0:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      max_depth: [None, 5, 10]
      max_features: ['auto', 'sqrt']
      min_samples_split: [2, 5, 10]
      n_estimators: [100, 200, 500]
    search_param_grid:
      max_depth:
        - None
        - 5
        - 10
      max_features:
        - 'auto'
        - 'sqrt'
      min_samples_split:
        - 2
        - 5
        - 10
      n_estimators:
        - 100
        - 200
        - 500

  module_1:
    class: XGBRegressor
    module: xgboost
    params:
      max_depth: [3, 6, 9]
      learning_rate: [0.01, 0.1, 0.2]
      n_estimators: [100, 200, 500]
    search_param_grid:
      max_depth:
        - 3
        - 6
        - 9
      learning_rate:
        - 0.01
        - 0.1
        - 0.2
      n_estimators:
        - 100
        - 200
        - 500

  module_2:
    class: AdaBoostRegressor
    module: sklearn.ensemble
    params:
      n_estimators: [50, 100, 200]
      learning_rate: [0.01, 0.1, 0.2]
    search_param_grid:
      n_estimators:
        - 50
        - 100
        - 200
      learning_rate:
        - 0.01
        - 0.1
        - 0.2
